### ISSUE TITLE
Would it be possible to show  thumbnails of images in this view?

### ISSUE THREAD

**Issue by fgrcon** [collective/wildcard.foldercontents#52]
For rearranging a large number of images this would be very helpfull.
Can anyone give a hint how to do this?

**Comment by vangheem** [comment]
Are you using 1.x or master(plone 5 backport).

If master, you can contribute here: https://github.com/plone/mockup/tree/master/mockup/patterns/structure

Maybe on delayed hover, show thumbnails for image types?

**Comment by fgrcon** [comment]
I first tried 1.3.1 but now switched to master, which looks phantastic and seems to work fine. First I will have to get a little bit deeper into mockup patterns, before i can contribute anything :-). 
My Idea would be to add a selectable column " thumbnail " and place tthe thums aswell in the rename form.

**Comment by fgrcon** [comment]
I first tried 1.3.1 but now switched to master, which looks phantastic and seems to work fine. First I will have to get a little bit deeper into mockup patterns, before i can contribute anything :-). 
My Idea would be to add a selectable column " thumbnail " and place tthe thums aswell in the rename form.

**Comment by vangheem** [comment]
Sounds good to me :)

**Comment by fgrcon** [comment]
moved to https://github.com/plone/Products.CMFPlone/issues/1074
