### ISSUE TITLE
problem uploading big files (only in 1.x branch)

### ISSUE THREAD

**Issue by cekk** [collective/wildcard.foldercontents#54]
If i try to upload a big file (about 20mb), i have the following error:

    AttributeError: 'file' object has no attribute 'filename'

The problem is that big files are chunked, and in [factory.py] (https://github.com/collective/wildcard.foldercontents/blob/1.x/wildcard/foldercontents/factories.py#L99) we don't have a ZPublisher file (with *filename* attribute), but a temp file (without that attribute).

I've seen that the last commits on 1.x branch are for a similar problem, but not exactly for that.
My fast and ugly workaround is in a temporary [branch] (https://github.com/collective/wildcard.foldercontents/blob/1.x-bigfiles/wildcard/foldercontents/factories.py#L98), but i think that this should be fixed in a different way.

Any suggestions?

**Comment by vangheem** [comment]
What version? I think I fixed the issue in 1.3.2

**Comment by cekk** [comment]
I thinked that it was fixed in 1.3.2 too, but i have this problem also with the code updated from github (branch 1.x).
Maybe is a different problem?

**Comment by vangheem** [comment]
Yes, this is weird and should not be happening. Nonetheless, your problem stems from my chunking changes.

I am using this in a couple live sites no problem for a while right now though. So yes, weird.

Even though it's a little wonky, I'm fine merging your fix--it's just a failsafe and more defensive code.

**Comment by agitator** [comment]
this looks solved to me, other opinions?
new release?

**Comment by vangheem** [comment]
Yes, I'll make a release.

**Comment by vangheem** [comment]
done.

**Comment by agitator** [comment]
thanx
